## SKlearn_Pipeline_GridSearchCV
### Data is taken from https://www.kaggle.com/c/house-prices-advanced-regression-techniques/data
### Data is about House Prices: Advanced Regression Techniques
### Data is only used for undestanding how to use  Pipeline and GridSearchCV during fitting model

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline


import warnings
warnings.filterwarnings("ignore")

/Users/mukeshchaudhary/opt/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)

In [2]:
# import data 

df = pd.read_csv("house-prices-advanced-regression-techniques/train.csv")
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [4]:
# check dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
Id               1460 non-null int64
MSSubClass       1460 non-null int64
MSZoning         1460 non-null object
LotFrontage      1201 non-null float64
LotArea          1460 non-null int64
Street           1460 non-null object
Alley            91 non-null object
LotShape         1460 non-null object
LandContour      1460 non-null object
Utilities        1460 non-null object
LotConfig        1460 non-null object
LandSlope        1460 non-null object
Neighborhood     1460 non-null object
Condition1       1460 non-null object
Condition2       1460 non-null object
BldgType         1460 non-null object
HouseStyle       1460 non-null object
OverallQual      1460 non-null int64
OverallCond      1460 non-null int64
YearBuilt        1460 non-null int64
YearRemodAdd     1460 non-null int64
RoofStyle        1460 non-null object
RoofMatl         1460 non-null object
Exterior1st      1460 non-null object
Exterior2nd      1460 non-null object
MasVnrType       1452 non-null object
MasVnrArea       1452 non-null float64
ExterQual        1460 non-null object
ExterCond        1460 non-null object
Foundation       1460 non-null object
BsmtQual         1423 non-null object
BsmtCond         1423 non-null object
BsmtExposure     1422 non-null object
BsmtFinType1     1423 non-null object
BsmtFinSF1       1460 non-null int64
BsmtFinType2     1422 non-null object
BsmtFinSF2       1460 non-null int64
BsmtUnfSF        1460 non-null int64
TotalBsmtSF      1460 non-null int64
Heating          1460 non-null object
HeatingQC        1460 non-null object
CentralAir       1460 non-null object
Electrical       1459 non-null object
1stFlrSF         1460 non-null int64
2ndFlrSF         1460 non-null int64
LowQualFinSF     1460 non-null int64
GrLivArea        1460 non-null int64
BsmtFullBath     1460 non-null int64
BsmtHalfBath     1460 non-null int64
FullBath         1460 non-null int64
HalfBath         1460 non-null int64
BedroomAbvGr     1460 non-null int64
KitchenAbvGr     1460 non-null int64
KitchenQual      1460 non-null object
TotRmsAbvGrd     1460 non-null int64
Functional       1460 non-null object
Fireplaces       1460 non-null int64
FireplaceQu      770 non-null object
GarageType       1379 non-null object
GarageYrBlt      1379 non-null float64
GarageFinish     1379 non-null object
GarageCars       1460 non-null int64
GarageArea       1460 non-null int64
GarageQual       1379 non-null object
GarageCond       1379 non-null object
PavedDrive       1460 non-null object
WoodDeckSF       1460 non-null int64
OpenPorchSF      1460 non-null int64
EnclosedPorch    1460 non-null int64
3SsnPorch        1460 non-null int64
ScreenPorch      1460 non-null int64
PoolArea         1460 non-null int64
PoolQC           7 non-null object
Fence            281 non-null object
MiscFeature      54 non-null object
MiscVal          1460 non-null int64
MoSold           1460 non-null int64
YrSold           1460 non-null int64
SaleType         1460 non-null object
SaleCondition    1460 non-null object
SalePrice        1460 non-null int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [5]:
# taking numerical data 

df_numerical = df.select_dtypes(exclude="object")
df_numerical.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,0,61,0,0,0,0,0,2,2008,208500
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,...,298,0,0,0,0,0,0,5,2007,181500
2,3,60,68.0,11250,7,5,2001,2002,162.0,486,...,0,42,0,0,0,0,0,9,2008,223500
3,4,70,60.0,9550,7,5,1915,1970,0.0,216,...,0,35,272,0,0,0,0,2,2006,140000
4,5,60,84.0,14260,8,5,2000,2000,350.0,655,...,192,84,0,0,0,0,0,12,2008,250000

In [8]:
# analyis numerical data 

df_numerical.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 38 columns):
Id               1460 non-null int64
MSSubClass       1460 non-null int64
LotFrontage      1201 non-null float64
LotArea          1460 non-null int64
OverallQual      1460 non-null int64
OverallCond      1460 non-null int64
YearBuilt        1460 non-null int64
YearRemodAdd     1460 non-null int64
MasVnrArea       1452 non-null float64
BsmtFinSF1       1460 non-null int64
BsmtFinSF2       1460 non-null int64
BsmtUnfSF        1460 non-null int64
TotalBsmtSF      1460 non-null int64
1stFlrSF         1460 non-null int64
2ndFlrSF         1460 non-null int64
LowQualFinSF     1460 non-null int64
GrLivArea        1460 non-null int64
BsmtFullBath     1460 non-null int64
BsmtHalfBath     1460 non-null int64
FullBath         1460 non-null int64
HalfBath         1460 non-null int64
BedroomAbvGr     1460 non-null int64
KitchenAbvGr     1460 non-null int64
TotRmsAbvGrd     1460 non-null int64
Fireplaces       1460 non-null int64
GarageYrBlt      1379 non-null float64
GarageCars       1460 non-null int64
GarageArea       1460 non-null int64
WoodDeckSF       1460 non-null int64
OpenPorchSF      1460 non-null int64
EnclosedPorch    1460 non-null int64
3SsnPorch        1460 non-null int64
ScreenPorch      1460 non-null int64
PoolArea         1460 non-null int64
MiscVal          1460 non-null int64
MoSold           1460 non-null int64
YrSold           1460 non-null int64
SalePrice        1460 non-null int64
dtypes: float64(3), int64(35)
memory usage: 433.6 KB

In [6]:
# taking categorical data 

df_categorical = df.select_dtypes(include="object")
df_categorical.head()

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
0,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
1,RL,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
2,RL,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
3,RL,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,...,Detchd,Unf,TA,TA,Y,NaN,NaN,NaN,WD,Abnorml
4,RL,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal

In [7]:
# analysis  df_categorical data 

df_categorical.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 43 columns):
MSZoning         1460 non-null object
Street           1460 non-null object
Alley            91 non-null object
LotShape         1460 non-null object
LandContour      1460 non-null object
Utilities        1460 non-null object
LotConfig        1460 non-null object
LandSlope        1460 non-null object
Neighborhood     1460 non-null object
Condition1       1460 non-null object
Condition2       1460 non-null object
BldgType         1460 non-null object
HouseStyle       1460 non-null object
RoofStyle        1460 non-null object
RoofMatl         1460 non-null object
Exterior1st      1460 non-null object
Exterior2nd      1460 non-null object
MasVnrType       1452 non-null object
ExterQual        1460 non-null object
ExterCond        1460 non-null object
Foundation       1460 non-null object
BsmtQual         1423 non-null object
BsmtCond         1423 non-null object
BsmtExposure     1422 non-null object
BsmtFinType1     1423 non-null object
BsmtFinType2     1422 non-null object
Heating          1460 non-null object
HeatingQC        1460 non-null object
CentralAir       1460 non-null object
Electrical       1459 non-null object
KitchenQual      1460 non-null object
Functional       1460 non-null object
FireplaceQu      770 non-null object
GarageType       1379 non-null object
GarageFinish     1379 non-null object
GarageQual       1379 non-null object
GarageCond       1379 non-null object
PavedDrive       1460 non-null object
PoolQC           7 non-null object
Fence            281 non-null object
MiscFeature      54 non-null object
SaleType         1460 non-null object
SaleCondition    1460 non-null object
dtypes: object(43)
memory usage: 490.6+ KB

In [10]:
# import some neccessary libraries from sklearn

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline

In [11]:
# check null value

df_numerical.isnull().sum()

Id                 0
MSSubClass         0
LotFrontage      259
LotArea            0
OverallQual        0
OverallCond        0
YearBuilt          0
YearRemodAdd       0
MasVnrArea         8
BsmtFinSF1         0
BsmtFinSF2         0
BsmtUnfSF          0
TotalBsmtSF        0
1stFlrSF           0
2ndFlrSF           0
LowQualFinSF       0
GrLivArea          0
BsmtFullBath       0
BsmtHalfBath       0
FullBath           0
HalfBath           0
BedroomAbvGr       0
KitchenAbvGr       0
TotRmsAbvGrd       0
Fireplaces         0
GarageYrBlt       81
GarageCars         0
GarageArea         0
WoodDeckSF         0
OpenPorchSF        0
EnclosedPorch      0
3SsnPorch          0
ScreenPorch        0
PoolArea           0
MiscVal            0
MoSold             0
YrSold             0
SalePrice          0
dtype: int64

In [12]:
# drop null

df_numerical.dropna(inplace=True)

In [13]:
df_numerical.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1121 entries, 0 to 1459
Data columns (total 38 columns):
Id               1121 non-null int64
MSSubClass       1121 non-null int64
LotFrontage      1121 non-null float64
LotArea          1121 non-null int64
OverallQual      1121 non-null int64
OverallCond      1121 non-null int64
YearBuilt        1121 non-null int64
YearRemodAdd     1121 non-null int64
MasVnrArea       1121 non-null float64
BsmtFinSF1       1121 non-null int64
BsmtFinSF2       1121 non-null int64
BsmtUnfSF        1121 non-null int64
TotalBsmtSF      1121 non-null int64
1stFlrSF         1121 non-null int64
2ndFlrSF         1121 non-null int64
LowQualFinSF     1121 non-null int64
GrLivArea        1121 non-null int64
BsmtFullBath     1121 non-null int64
BsmtHalfBath     1121 non-null int64
FullBath         1121 non-null int64
HalfBath         1121 non-null int64
BedroomAbvGr     1121 non-null int64
KitchenAbvGr     1121 non-null int64
TotRmsAbvGrd     1121 non-null int64
Fireplaces       1121 non-null int64
GarageYrBlt      1121 non-null float64
GarageCars       1121 non-null int64
GarageArea       1121 non-null int64
WoodDeckSF       1121 non-null int64
OpenPorchSF      1121 non-null int64
EnclosedPorch    1121 non-null int64
3SsnPorch        1121 non-null int64
ScreenPorch      1121 non-null int64
PoolArea         1121 non-null int64
MiscVal          1121 non-null int64
MoSold           1121 non-null int64
YrSold           1121 non-null int64
SalePrice        1121 non-null int64
dtypes: float64(3), int64(35)
memory usage: 341.6 KB

In [15]:
# now split data 

X = df_numerical.drop("SalePrice",axis=1)
y = df_numerical['SalePrice']

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.25)

In [18]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)

(840, 37)
(281, 37)
(840,)

In [23]:
# Scaling

sc = StandardScaler()

X_train_scale = sc.fit_transform(X_train)

X_train_scale

array([[ 0.10528099, -0.86379585,  1.62260168, ..., -0.12866102,
         0.24121139, -0.58682311],
       [-1.20934711, -0.86379585,  0.11008113, ..., -0.12866102,
        -0.86800887, -1.33824295],
       [ 0.4351245 ,  0.79442146,  0.47799153, ..., -0.12866102,
         0.61095147, -0.58682311],
       ...,
       [ 1.67856335, -0.86379585,  1.05029661, ..., -0.12866102,
         1.72017173,  0.16459673],
       [-0.8605198 ,  0.55753327,  1.25469128, ..., -0.12866102,
         2.08991182,  0.16459673],
       [-1.56292038, -0.86379585, -0.05343461, ..., -0.12866102,
        -0.1285287 , -0.58682311]])

In [24]:
# initialize model

rf = RandomForestClassifier()

rf.fit(X_train_scale,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [25]:
rf.score(X_train_scale,y_train)

1.0

In [26]:
rf.score(X_train,y_train)

0.010714285714285714

In [29]:
# When use pipeline class

pipeline = Pipeline([( "scaler" , StandardScaler()),
                       ("rf",RandomForestClassifier())])



# fit train data 

pipeline.fit(X_train,y_train)

pipeline.score(X_train,y_train)

pipeline.predict(X_test)

array([135000, 140000, 155000, 385000, 127000, 149900, 129500, 402000,
       100000, 135000, 160000, 175900, 145000, 173500, 155000, 100000,
       153500, 176000, 325000, 192000, 155000, 175000, 101000,  99500,
       119000, 348000, 360000, 130000, 100000, 295493, 110000, 178000,
       145000, 135000, 191000, 175000, 124000, 140000, 180000, 186500,
       133000, 124500,  75000,  73000, 130000, 180000, 137000, 128000,
       260000, 227000, 118400, 250000, 113000, 152000, 290000, 125000,
       133000, 135000, 145000, 339750, 217000, 312500, 312500,  68500,
       339750, 277500, 142500, 185850, 250580, 197000, 192000, 274900,
       139000, 156000, 179600, 230000, 130500, 140000, 215200, 215000,
       181000, 207500, 140000, 135000,  92900, 195000, 108000, 109000,
       314813, 290000, 192000, 116050, 153000, 154900, 238000, 140000,
       130000, 174000, 152000, 129500, 169000, 150900, 142600, 139000,
       215000, 415298,  87000, 133000, 325000, 180500, 360000, 250000,
       187100, 135000,  91000, 190000, 118964, 140200, 120500, 135000,
       141000, 117000, 162000, 140000, 112000, 119000, 185500, 395192,
       110000, 130000, 239000, 239686, 250000, 153000, 250000, 293077,
       232600, 395192, 155000, 176000, 155835, 160000, 165000, 124000,
       297000, 124000, 245000, 110000, 167000, 200141, 271000, 129500,
       226700, 118400, 140000, 223500, 250000, 139000, 119000, 130000,
       148000, 195400, 135000, 116000, 112500, 244000, 100000, 155000,
       175000, 170000, 555000, 232000, 137900, 137000, 119000, 135000,
       266000, 187100, 178000, 129500, 239000, 153000, 180000, 167000,
       101800, 109000, 440000, 100000, 437154, 140000, 119000, 260000,
       204000,  89500, 169990, 290000, 110000, 153337, 155000, 178000,
       180000, 137500, 155000, 124900, 155000, 126000, 145000, 119000,
       190000, 119000, 122500, 290000, 290000, 185000, 270000, 183000,
       207000, 115000, 155000, 132500, 290000, 275000, 155000, 108000,
       135000, 220000, 250000, 227000, 137000, 135000, 139000, 148500,
       160000, 253293, 127000, 100000, 137000, 227000, 200141, 100000,
       175500, 202665, 165500, 227000, 176000, 188000, 290000, 244000,
       116050, 250000, 129500, 224500, 159895, 140000, 187750, 159500,
       230000, 301500, 119000, 112500, 305000, 178000,  76000, 114504,
        92900, 138500, 290000, 236000, 155000, 165400, 250000, 202665,
       124500, 140000, 145000, 222500, 195000, 335000, 129000, 155000,
       189000])